#if !defined(BLOCK_ID_MAPPING)
#define BLOCK_ID_MAPPING
// This file was automatically generated by block_wrangler


bool sway(int id) {
	return id == 1001 || id == 1002 || id == 1003;
}


bool sway_bottom(int id) {
	return id == 1001 || id == 1002;
}


bool crops(int id) {
	return id == 1001;
}


bool water(int id) {
	return id == 1000;
}


#endif // BLOCK_ID_MAPPING