import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {

  tutorialSidebar: [
    'quickstart',
    'overview',
    {
      type: 'category',
      label: 'Basic Usage',
      items: [
        {
          type: 'autogenerated',
          dirName: 'basic_usage',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Usage',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced_usage',
        },
      ],
    },
    {
      type: 'category',
      label: 'Library',
      items: [
        {
          type: 'autogenerated',
          dirName: 'library',
        },
      ],
    },
  ],
};

export default sidebars;
